dist: trusty

language: php

## Cache composer downloads.
cache:
  directories:
    - $HOME/.cache/composer/files

php:
  - 5.4
  - 7.4

matrix:
  fast_finish: true

before_install:
  # Speed up build time by disabling Xdebug when its not needed.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  - composer install

script:
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict
